export default defineNuxtConfig({
  ssr: true,
  modules: ['@nuxtjs/tailwindcss'],
  devtools: { enabled: true },
  nitro: {
    prerender: {
      autoSubfolderIndex: false,
      crawlLinks: true,
      routes: [
        '/',
        '/about',
        '/privacy-policy',
        '/terms',
        '/contact',
        '/how-it-works',
        '/image-watermark-remover',
        '/video-watermark-remover',
        '/nano-banana-watermark-remover',
        '/veo-watermark-remover',
        '/google-flow-watermark-remover',
        '/blog',
        '/blog/google-removes-visible-gemini-watermark',
        '/blog/how-to-remove-gemini-watermark',
        '/blog/why-google-watermarks-gemini-images',
        '/blog/gemini-vs-chatgpt-vs-midjourney-watermark',
        '/blog/remove-gemini-watermark-photoshop',
        '/blog/remove-gemini-watermark-gimp',
        '/blog/synthid-vs-visible-watermark',
        '/blog/gemini-watermark-chrome-extension-vs-online-tool',
        '/blog/remove-gemini-watermark-youtube-thumbnail',
        '/blog/remove-gemini-watermark-print-on-demand',
        '/blog/remove-gemini-watermark-social-media',
        '/blog/reverse-alpha-blending-explained',
        '/sitemap.xml',
        '/robots.txt',
        '/og/index.png',
        '/og/image-watermark-remover.png',
        '/og/video-watermark-remover.png',
        '/og/nano-banana-watermark-remover.png',
        '/og/veo-watermark-remover.png',
        '/og/google-flow-watermark-remover.png',
        '/og/how-it-works.png',
        '/og/about.png',
        '/og/contact.png',
        '/og/privacy-policy.png',
        '/og/terms.png',
        '/og/blog.png',
        '/og/blog/index.png',
        '/og/blog/google-removes-visible-gemini-watermark.png',
        '/og/blog/how-to-remove-gemini-watermark.png',
        '/og/blog/why-google-watermarks-gemini-images.png',
        '/og/blog/gemini-vs-chatgpt-vs-midjourney-watermark.png',
        '/og/blog/remove-gemini-watermark-photoshop.png',
        '/og/blog/remove-gemini-watermark-gimp.png',
        '/og/blog/synthid-vs-visible-watermark.png',
        '/og/blog/gemini-watermark-chrome-extension-vs-online-tool.png',
        '/og/blog/remove-gemini-watermark-youtube-thumbnail.png',
        '/og/blog/remove-gemini-watermark-print-on-demand.png',
        '/og/blog/remove-gemini-watermark-social-media.png',
        '/og/blog/reverse-alpha-blending-explained.png',
      ],
    },
  },
  app: {
    head: {
      htmlAttrs: { lang: 'en' },
      titleTemplate: '%s | Watermark Remover',
      title: 'Free Gemini Watermark Remover — AI Image & Video',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        {
          name: 'description',
          content:
            '100% free Gemini watermark remover — strip the Gemini, Veo, Imagen, Nano Banana & Google Flow sparkle from images and videos. No upload, no signup, no limits.',
        },
        {
          name: 'keywords',
          content:
            'gemini watermark remover, remove gemini watermark, ai watermark remover, veo watermark remover, nano banana watermark remover, imagen watermark remover, google flow watermark remover, reverse alpha blending, synthid',
        },
        { name: 'author', content: 'Arshad Akl' },
        { name: 'robots', content: 'index, follow, max-image-preview:large, max-snippet:-1' },
        { name: 'theme-color', content: '#0a0a0a' },
        { name: 'application-name', content: 'Gemini Watermark Remover' },
        { name: 'apple-mobile-web-app-title', content: 'Watermark Remover' },
        { name: 'format-detection', content: 'telephone=no' },
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Watermark Remover' },
        { property: 'og:locale', content: 'en_US' },
        {
          property: 'og:title',
          content: 'Free Gemini Watermark Remover — AI Image & Video',
        },
        {
          property: 'og:description',
          content:
            '100% free — strip the Gemini, Veo, Imagen, Nano Banana & Google Flow sparkle from AI images and videos. No upload, no signup, no limits.',
        },
        { property: 'og:image', content: 'https://watermark-remover.arshadakl.in/og/index.png' },
        { property: 'og:image:secure_url', content: 'https://watermark-remover.arshadakl.in/og/index.png' },
        { property: 'og:image:type', content: 'image/png' },
        { property: 'og:image:width', content: '1200' },
        { property: 'og:image:height', content: '630' },
        { property: 'og:image:alt', content: 'Gemini Watermark Remover' },
        { property: 'og:url', content: 'https://watermark-remover.arshadakl.in/' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:title', content: 'Free Gemini Watermark Remover — AI Image & Video' },
        {
          name: 'twitter:description',
          content: '100% free Gemini watermark remover — no upload, no signup, no limits. Works on Gemini, Veo, Imagen, Nano Banana & Google Flow.',
        },
        { name: 'twitter:image', content: 'https://watermark-remover.arshadakl.in/og-image.png' },
        { name: 'twitter:image:alt', content: 'Gemini Watermark Remover' },
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
        { rel: 'apple-touch-icon', sizes: '180x180', href: '/apple-touch-icon.png' },
        { rel: 'manifest', href: '/site.webmanifest' },
        { rel: 'canonical', href: 'https://watermark-remover.arshadakl.in/' },
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap',
        },
      ],
      script: [
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'WebApplication',
            name: 'Gemini Watermark Remover',
            url: 'https://watermark-remover.arshadakl.in',
            applicationCategory: 'MultimediaApplication',
            operatingSystem: 'Any modern browser',
            offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
            description:
              'Remove the Gemini AI sparkle watermark from images and videos. 100% client-side, no upload, no signup. Supports Gemini, Veo, Imagen, Nano Banana and Google Flow.',
            browserRequirements:
              'Requires Canvas API (images) and WebCodecs API (video, Chrome/Edge/Brave 94+).',
            aggregateRating: {
              '@type': 'AggregateRating',
              ratingValue: '4.9',
              reviewCount: '240',
            },
          }),
        },
        {
          type: 'application/ld+json',
          innerHTML: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'Organization',
            name: 'Watermark Remover',
            url: 'https://watermark-remover.arshadakl.in',
            logo: 'https://watermark-remover.arshadakl.in/favicon.svg',
            sameAs: ['https://arshadakl.in'],
          }),
        },
      ],
    },
  },
})
