<script setup lang="ts">
const route = useRoute()
const siteUrl = 'https://watermark-remover.arshadakl.in'
const pageUrl = siteUrl + route.path

useSeoMeta({
  title: 'About — Watermark Remover',
  description:
    'Watermark Remover is a free, browser-based tool for stripping the Gemini, Veo, Imagen, Nano Banana, and Google Flow sparkle from AI-generated images and videos. Built by Arshad.',
  ogTitle: 'About Watermark Remover',
  ogDescription: 'A free, browser-based Gemini watermark remover. Built by Arshad. No upload, no signup.',
  ogImage: `${siteUrl}/og/about.svg`,
  ogUrl: pageUrl,
  twitterCard: 'summary_large_image',
})

useHead({
  link: [{ rel: 'canonical', href: pageUrl }],
  script: [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'AboutPage',
        name: 'About Watermark Remover',
        url: pageUrl,
        description: 'About the Watermark Remover tool.',
        mainEntity: {
          '@type': 'Organization',
          name: 'Watermark Remover',
          url: siteUrl,
          founder: { '@type': 'Person', name: 'Arshad', url: 'https://arshadakl.in' },
        },
      }),
    },
  ],
})
</script>

<template>
  <div class="min-h-screen bg-[#0a0a0a]">
    <SiteNav />
    <div class="h-16" />

    <section class="relative overflow-hidden pt-12 pb-12">
      <div class="absolute inset-0 bg-gradient-to-b from-brand-500/5 to-transparent" />
      <div class="relative mx-auto max-w-3xl px-6 text-center">
        <div class="mb-5 inline-flex items-center gap-2 rounded-full border border-brand-500/20 bg-brand-500/10 px-4 py-1.5 text-xs font-medium text-brand-400">
          About this project
        </div>
        <h1 class="mb-6 text-4xl font-bold leading-tight tracking-tight md:text-5xl">
          About <span class="text-brand-400">Watermark Remover</span>
        </h1>
      </div>
    </section>

    <article class="py-12">
      <div class="mx-auto max-w-3xl px-6 space-y-6 leading-relaxed text-gray-300">
        <p>
          Watermark Remover is a free, browser-based tool for stripping the Gemini, Veo, Imagen, Nano Banana, and Google Flow sparkle watermark from AI-generated images and videos. It runs entirely in your browser using the Canvas API for images and the WebCodecs API for video — no upload, no server, no signup, no quota.
        </p>

        <h2 class="text-2xl font-bold text-white">Why we built it</h2>
        <p>
          Every image and video generated by Google's AI tools ships with a small four-point sparkle in the bottom-right corner. For personal experiments that is fine. For client work — mockups, ad creative, presentations, posters, book covers, YouTube thumbnails — the sparkle reads as a vendor logo on a deliverable. Cropping it out changes the composition. Blurring it leaves an obvious patch. General AI inpainting smears the detail.
        </p>
        <p>
          The right answer is to reverse the math Google used to apply the watermark in the first place. That is what this site does, in your browser, without sending a single pixel to a server.
        </p>

        <h2 class="text-2xl font-bold text-white">How it works under the hood</h2>
        <p>
          The watermark is a fixed logo composited onto every Gemini output with a known alpha map. Reverse the blend equation pixel-wise and the original pixels come back. No AI guesswork, no generative model — just algebra. The result is byte-identical to the source outside the watermark zone, with no smear on textured backgrounds.
        </p>
        <p>
          Video works the same way, frame by frame, with the original audio preserved bit-for-bit. Read the technical walkthrough on the <NuxtLink to="/how-it-works" class="text-brand-400 transition hover:text-brand-300">How it works</NuxtLink> page.
        </p>

        <h2 class="text-2xl font-bold text-white">Tech stack</h2>
        <ul class="list-disc space-y-2 pl-6 text-sm text-gray-400">
          <li><strong class="text-white">Nuxt 3</strong> (static-prerendered SPA) for fast page loads and SEO-friendly HTML.</li>
          <li><strong class="text-white">WebCodecs API</strong> for hardware-accelerated video decode and encode.</li>
          <li><strong class="text-white">mp4box.js</strong> for demuxing the source MP4 into audio and video samples.</li>
          <li><strong class="text-white">mp4-muxer</strong> for muxing the cleaned video with the original audio.</li>
          <li><strong class="text-white">Canvas API</strong> for image reading, processing, and PNG export.</li>
          <li><strong class="text-white">Tailwind CSS</strong> for the dark, minimal UI.</li>
        </ul>

        <h2 class="text-2xl font-bold text-white">Privacy</h2>
        <p>
          The tool collects nothing. No analytics, no cookies, no telemetry. Your images and videos are read into browser memory, processed in place, and written to a downloadable blob — the same flow as a calculator on your desktop. See the full <NuxtLink to="/privacy-policy" class="text-brand-400 transition hover:text-brand-300">Privacy Policy</NuxtLink> for the legal version of this paragraph.
        </p>

        <h2 class="text-2xl font-bold text-white">Who built it</h2>
        <p>
          This site is built by <a href="https://arshadakl.in" target="_blank" rel="noopener noreferrer" class="text-brand-400 transition hover:text-brand-300">Arshad</a>, an independent developer working on practical, privacy-respecting web tools. The project is not affiliated with, endorsed by, or sponsored by Google, Alphabet, or any of their products. Gemini, Veo, Imagen, Nano Banana, and Google Flow are trademarks of Google LLC.
        </p>

        <h2 class="text-2xl font-bold text-white">Use responsibly</h2>
        <p>
          This tool exists to help you clean up images and videos <strong class="text-white">you generated yourself</strong> on Google AI surfaces. Please do not use it to strip watermarks from copyrighted material belonging to others, or to misrepresent AI-generated content as something it is not. If you publish an AI-generated image publicly, common sense — and increasingly regulators — require you to disclose that the image is AI-generated regardless of whether the visible sparkle is present.
        </p>

        <div class="rounded-3xl border border-brand-500/20 bg-brand-500/[0.03] p-6">
          <p class="text-sm text-gray-400">
            Have a feature request, a bug report, or a question? Head to the <NuxtLink to="/contact" class="text-brand-400 transition hover:text-brand-300">Contact</NuxtLink> page.
          </p>
        </div>
      </div>
    </article>

    <SiteFooter />
  </div>
</template>
