<script setup lang="ts">
const route = useRoute()
const siteUrl = 'https://watermark-remover.arshadakl.in'
const pageUrl = siteUrl + route.path

useSeoMeta({
  title: 'Google Flow Watermark Remover — Free, Browser-Based',
  description:
    'Strip the Gemini and Veo sparkle watermark from Google Flow video exports. Frame-by-frame reverse alpha-blend, audio preserved, 100% in your browser.',
  ogTitle: 'Google Flow Watermark Remover — Free',
  ogDescription: 'Clean the Gemini/Veo sparkle from every Flow export. Free, browser-based, no upload.',
  ogImage: `${siteUrl}/og/google-flow-watermark-remover.png`,
  ogUrl: pageUrl,
  twitterCard: 'summary_large_image',
})

useHead({
  link: [{ rel: 'canonical', href: pageUrl }],
})
</script>

<template>
  <div class="min-h-screen bg-[#0a0a0a]">
    <SiteNav />
    <div class="h-16" />

    <section class="relative overflow-hidden pt-12 pb-16">
      <div class="absolute inset-0 bg-gradient-to-b from-brand-500/5 to-transparent" />
      <div class="relative mx-auto max-w-4xl px-6 text-center">
        <div class="mb-5 inline-flex items-center gap-2 rounded-full border border-brand-500/20 bg-brand-500/10 px-4 py-1.5 text-xs font-medium text-brand-400">
          For Google Flow filmmaking exports
        </div>
        <h1 class="mb-6 text-4xl font-bold leading-tight tracking-tight md:text-5xl">
          Google Flow <span class="text-brand-400">Watermark Remover</span>
        </h1>
        <p class="mx-auto mb-8 max-w-2xl text-lg text-gray-400">
          Google Flow is Google's AI filmmaking workspace for creating clips and scenes with Veo, Imagen, and Gemini. Depending on the model and account type, an exported Flow video can include a visible Gemini or Veo mark in the frame. This tool cleans it up — frame by frame, in your browser.
        </p>
        <NuxtLink
          to="/"
          class="inline-flex items-center gap-2 rounded-full bg-brand-500 px-7 py-3 text-sm font-semibold text-black transition hover:bg-brand-400"
        >
          Open the video tool
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
          </svg>
        </NuxtLink>
      </div>
    </section>

    <section class="py-16">
      <div class="mx-auto max-w-4xl px-6">
        <p class="mb-2 text-xs font-semibold uppercase tracking-wider text-brand-400">What is Google Flow?</p>
        <h2 class="mb-6 text-3xl font-bold">Flow = Gemini + Veo + Imagen, in one editor</h2>
        <p class="mb-6 leading-relaxed text-gray-400">
          Flow is Google's filmmaking workspace. It stitches together clips generated by Veo, Imagen, and the wider Gemini family, with editing tools designed for short-form cinematic work. Most free accounts and many paid accounts still see the same Gemini sparkle watermark on exported clips, because Flow reuses the underlying generation models' watermarking pipeline.
        </p>
        <p class="leading-relaxed text-gray-400">
          A general-purpose video editor can crop or blur the corner, but those shortcuts change the composition and usually leave an obvious patch. The reverse alpha-blend pipeline used here targets the watermark itself: it lifts the same logo Veo stamps, on every frame, with no smear or flicker.
        </p>
      </div>
    </section>

    <section class="py-16">
      <div class="mx-auto max-w-4xl px-6">
        <p class="mb-2 text-xs font-semibold uppercase tracking-wider text-brand-400">Workflow</p>
        <h2 class="mb-6 text-3xl font-bold">From Flow export to clean clip in three steps</h2>
        <ol class="space-y-4">
          <li class="flex gap-4 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-sm font-bold text-brand-400">1</div>
            <div>
              <h3 class="mb-1 text-sm font-semibold">Export the original from Flow</h3>
              <p class="text-xs leading-relaxed text-gray-500">Use the original-quality MP4 export from Google Flow. Avoid re-encoding or screenshotting — that compresses the watermark area and makes detection harder.</p>
            </div>
          </li>
          <li class="flex gap-4 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-sm font-bold text-brand-400">2</div>
            <div>
              <h3 class="mb-1 text-sm font-semibold">Open the video tool</h3>
              <p class="text-xs leading-relaxed text-gray-500">Drop the MP4 into this page in the Video tab. The tool decodes a calibration frame at about 15% into the timeline to find the watermark position.</p>
            </div>
          </li>
          <li class="flex gap-4 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-sm font-bold text-brand-400">3</div>
            <div>
              <h3 class="mb-1 text-sm font-semibold">Download the clean clip</h3>
              <p class="text-xs leading-relaxed text-gray-500">The cleaned MP4 keeps the original resolution, frame rate, bitrate, and audio. No re-encode penalty.</p>
            </div>
          </li>
        </ol>
      </div>
    </section>

    <section class="py-16">
      <div class="mx-auto max-w-4xl px-6">
        <div class="rounded-3xl border border-brand-500/20 bg-brand-500/[0.03] p-8">
          <h2 class="mb-3 text-xl font-bold">Same tool, same Flow footage</h2>
          <p class="text-sm leading-relaxed text-gray-400">
            Because Flow exports use the Veo watermark under the hood, you don't need a separate Flow-specific tool. The same Veo pipeline that cleans a Veo 3 export from gemini.google.com also cleans a Flow clip exported from flow.google.com. Drop the file in, get a clean file out.
          </p>
        </div>
      </div>
    </section>

    <SiteFooter />
  </div>
</template>
