<script setup lang="ts">
const route = useRoute()
const siteUrl = 'https://watermark-remover.arshadakl.in'
const pageUrl = siteUrl + route.path

useSeoMeta({
  title: 'Gemini Image Watermark Remover — Free, Private, Pixel-Perfect',
  description:
    'Free online tool to remove the Gemini, Imagen, and Nano Banana sparkle watermark from images. Reverse alpha blending, no upload, no signup, supports PNG, JPG, WEBP, GIF.',
  ogTitle: 'Gemini Image Watermark Remover — Free & Private',
  ogDescription: 'Strip the Gemini sparkle from any image in seconds. 100% browser-based, pixel-perfect.',
  ogImage: `${siteUrl}/og-image.png`,
  ogUrl: pageUrl,
  twitterCard: 'summary_large_image',
})

useHead({
  link: [{ rel: 'canonical', href: pageUrl }],
  script: [
    {
      type: 'application/ld+json',
      innerHTML: JSON.stringify({
        '@context': 'https://schema.org',
        '@type': 'HowTo',
        name: 'How to remove the Gemini watermark from an image',
        description: 'Strip the visible Gemini, Imagen, or Nano Banana sparkle watermark from an image using reverse alpha blending in the browser.',
        step: [
          { '@type': 'HowToStep', name: 'Open the tool', text: 'Navigate to the Gemini Watermark Remover.' },
          { '@type': 'HowToStep', name: 'Upload your image', text: 'Drag and drop or click to upload a PNG, JPG, WEBP, or GIF generated by Gemini, Imagen, or Nano Banana.' },
          { '@type': 'HowToStep', name: 'Detect watermark', text: 'The tool scans the bottom-right corner using normalized cross-correlation to find the sparkle at either 48x48 or 96x96.' },
          { '@type': 'HowToStep', name: 'Reverse alpha blend', text: 'The original pixel values under the watermark are recovered mathematically — no AI guessing.' },
          { '@type': 'HowToStep', name: 'Download clean PNG', text: 'Save the cleaned image at its original resolution.' },
        ],
      }),
    },
  ],
})
</script>

<template>
  <div class="min-h-screen bg-[#0a0a0a]">
    <SiteNav />
    <div class="h-16" />

    <!-- Hero -->
    <section class="relative overflow-hidden pt-12 pb-16">
      <div class="absolute inset-0 bg-gradient-to-b from-brand-500/5 to-transparent" />
      <div class="relative mx-auto max-w-4xl px-6 text-center">
        <div class="mb-5 inline-flex items-center gap-2 rounded-full border border-brand-500/20 bg-brand-500/10 px-4 py-1.5 text-xs font-medium text-brand-400">
          Image tool · 100% browser-based
        </div>
        <h1 class="mb-6 text-4xl font-bold leading-tight tracking-tight md:text-5xl">
          Gemini <span class="text-brand-400">Image Watermark Remover</span>
        </h1>
        <p class="mx-auto mb-8 max-w-2xl text-lg text-gray-400">
          Strip the Gemini, Imagen, and Nano Banana sparkle watermark from any image — automatically, losslessly, in your browser. No upload, no signup, pixel-perfect output.
        </p>
        <NuxtLink
          to="/"
          class="inline-flex items-center gap-2 rounded-full bg-brand-500 px-7 py-3 text-sm font-semibold text-black transition hover:bg-brand-400"
        >
          Open the image tool
          <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
            <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
          </svg>
        </NuxtLink>
      </div>
    </section>

    <!-- What it removes -->
    <section class="py-16">
      <div class="mx-auto max-w-4xl px-6">
        <p class="mb-2 text-xs font-semibold uppercase tracking-wider text-brand-400">What it removes</p>
        <h2 class="mb-6 text-3xl font-bold">The visible sparkle from every Google image model</h2>
        <p class="mb-8 leading-relaxed text-gray-400">
          Every AI-generated image from Gemini, Imagen, or Nano Banana ships with a small four-point sparkle logo in the bottom-right corner. The detector on this page finds it automatically — at either the legacy <strong class="text-white">48×48</strong> size or the newer <strong class="text-white">96×96</strong> size used by Gemini 2.0 Flash and later — then reverses the alpha-blend equation Google used to stamp it. The result is byte-identical to the original outside the watermark zone, with no AI inpainting guesswork and no quality loss.
        </p>

        <div class="grid gap-4 md:grid-cols-3">
          <div class="rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <h3 class="mb-2 text-sm font-semibold">PNG</h3>
            <p class="text-xs text-gray-500">Lossless export. Best for screenshots and high-quality work.</p>
          </div>
          <div class="rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <h3 class="mb-2 text-sm font-semibold">JPG / JPEG</h3>
            <p class="text-xs text-gray-500">Compressed exports from Gemini. Output stays at original quality.</p>
          </div>
          <div class="rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <h3 class="mb-2 text-sm font-semibold">WEBP / GIF</h3>
            <p class="text-xs text-gray-500">Modern web formats and animated exports.</p>
          </div>
        </div>
      </div>
    </section>

    <!-- How it works (image-specific) -->
    <section class="py-16">
      <div class="mx-auto max-w-4xl px-6">
        <p class="mb-2 text-xs font-semibold uppercase tracking-wider text-brand-400">How it works</p>
        <h2 class="mb-10 text-3xl font-bold">Four steps, all in your browser</h2>
        <ol class="space-y-4">
          <li class="flex gap-4 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-sm font-bold text-brand-400">1</div>
            <div>
              <h3 class="mb-1 text-sm font-semibold">Drop your Gemini image</h3>
              <p class="text-xs leading-relaxed text-gray-500">Click the upload zone or drag a file in. Anything PNG, JPG, WEBP, or GIF works at any resolution.</p>
            </div>
          </li>
          <li class="flex gap-4 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-sm font-bold text-brand-400">2</div>
            <div>
              <h3 class="mb-1 text-sm font-semibold">Detect the watermark</h3>
              <p class="text-xs leading-relaxed text-gray-500">Normalized cross-correlation scans the bottom-right corner to find the sparkle. The 48×48 and 96×96 alpha maps are baked into the page so detection takes milliseconds.</p>
            </div>
          </li>
          <li class="flex gap-4 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-sm font-bold text-brand-400">3</div>
            <div>
              <h3 class="mb-1 text-sm font-semibold">Reverse the blend</h3>
              <p class="text-xs leading-relaxed text-gray-500">For every pixel under the watermark, the original value is recovered with <code class="text-brand-400">original = (pixel - α × 255) / (1 - α)</code>. Edge diffusion smooths the seam.</p>
            </div>
          </li>
          <li class="flex gap-4 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
            <div class="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-brand-500/20 text-sm font-bold text-brand-400">4</div>
            <div>
              <h3 class="mb-1 text-sm font-semibold">Download the clean image</h3>
              <p class="text-xs leading-relaxed text-gray-500">Click <em>Download</em> to save the cleaned PNG. Original resolution, original quality, original filename prefix <code class="text-brand-400">cleaned-</code>.</p>
            </div>
          </li>
        </ol>
      </div>
    </section>

    <!-- Privacy callout -->
    <section class="py-16">
      <div class="mx-auto max-w-4xl px-6">
        <div class="rounded-3xl border border-brand-500/20 bg-brand-500/[0.03] p-8">
          <h2 class="mb-3 text-2xl font-bold">Your images never leave your device</h2>
          <p class="text-sm leading-relaxed text-gray-400">
            The watermark removal pipeline runs entirely in your browser using the Canvas API. The image is read into memory, processed, and written to a downloadable blob — no server, no upload, no third party. Even the alpha masks are bundled with the page, so there is no remote fetch at any point. This is the same browser-only architecture used by tools like removewatermarkgemini.com, but it stays free without quotas, signups, or watermarks of its own.
          </p>
        </div>
      </div>
    </section>

    <!-- Related links -->
    <section class="py-16">
      <div class="mx-auto max-w-4xl px-6">
        <p class="mb-6 text-xs font-semibold uppercase tracking-wider text-brand-400">Related tools</p>
        <div class="grid gap-4 md:grid-cols-2">
          <NuxtLink to="/video-watermark-remover" class="rounded-2xl border border-white/5 bg-white/[0.02] p-5 transition hover:border-brand-500/20">
            <h3 class="mb-1 text-sm font-semibold">Video watermark remover →</h3>
            <p class="text-xs text-gray-500">Strip the sparkle from Veo and Google Flow videos, frame by frame.</p>
          </NuxtLink>
          <NuxtLink to="/nano-banana-watermark-remover" class="rounded-2xl border border-white/5 bg-white/[0.02] p-5 transition hover:border-brand-500/20">
            <h3 class="mb-1 text-sm font-semibold">Nano Banana watermark remover →</h3>
            <p class="text-xs text-gray-500">Targeted tool for Google's newest image model.</p>
          </NuxtLink>
          <NuxtLink to="/blog/how-to-remove-gemini-watermark" class="rounded-2xl border border-white/5 bg-white/[0.02] p-5 transition hover:border-brand-500/20">
            <h3 class="mb-1 text-sm font-semibold">How-to guide →</h3>
            <p class="text-xs text-gray-500">Step-by-step written walkthrough with screenshots.</p>
          </NuxtLink>
          <NuxtLink to="/blog/reverse-alpha-blending-explained" class="rounded-2xl border border-white/5 bg-white/[0.02] p-5 transition hover:border-brand-500/20">
            <h3 class="mb-1 text-sm font-semibold">Reverse alpha blending →</h3>
            <p class="text-xs text-gray-500">The exact math behind why the result is lossless.</p>
          </NuxtLink>
        </div>
      </div>
    </section>

    <SiteFooter />
  </div>
</template>
